In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px 
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)
plt.style.use('ggplot')

In [36]:
# Import the data
df = pd.read_csv('NYPD_Complaint_Data_Historic.csv')
df.head()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1568\2160679100.py:2: DtypeWarning: Columns (18,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('NYPD_Complaint_Data_Historic.csv')

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,BORO_NM,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,JURIS_DESC,JURISDICTION_CODE,PARKS_NM,HADEVELOPT,HOUSING_PSA,X_COORD_CD,Y_COORD_CD,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
0,724718389,09/04/2014,17:25:00,09/04/2014,17:35:00,81.0,09/04/2014,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,BROOKLYN,OPPOSITE OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1005945.0,188862.0,NaN,NaN,NaN,NaN,40.685041,-73.921777,"(40.685040958, -73.921776995)",PATROL BORO BKLYN NORTH,NaN,25-44,WHITE,F
1,191133903,10/12/2016,07:40:00,10/12/2016,07:45:00,121.0,10/12/2016,109,GRAND LARCENY,417.0,"LARCENY,GRAND FROM PERSON,PURS",COMPLETED,FELONY,STATEN ISLAND,NaN,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,947034.0,171375.0,UNKNOWN,BLACK,U,NaN,40.636991,-74.134093,"(40.63699139, -74.134092508)",PATROL BORO STATEN ISLAND,NaN,45-64,WHITE HISPANIC,F
2,720151206,09/28/2012,13:30:00,09/28/2012,14:00:00,41.0,10/19/2012,109,GRAND LARCENY,413.0,"LARCENY,GRAND BY FALSE PROMISE",COMPLETED,FELONY,BRONX,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1014179.0,239453.0,NaN,WHITE HISPANIC,M,NaN,40.823876,-73.891863,"(40.823876276, -73.891862968)",PATROL BORO BRONX,NaN,45-64,WHITE HISPANIC,F
3,232242098,03/24/2015,15:45:00,NaN,NaN,46.0,03/24/2015,341,PETIT LARCENY,339.0,"LARCENY,PETIT FROM OPEN AREAS,",COMPLETED,MISDEMEANOR,BRONX,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1009041.0,247401.0,NaN,BLACK,M,NaN,40.845707,-73.910398,"(40.845707148, -73.910398033)",PATROL BORO BRONX,NaN,<18,WHITE HISPANIC,F
4,708078702,05/20/2017,04:02:00,05/20/2017,04:09:00,109.0,05/20/2017,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,QUEENS,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1031779.0,217663.0,25-44,WHITE HISPANIC,M,NaN,40.763992,-73.828426,"(40.763991557, -73.828425559)",PATROL BORO QUEENS NORTH,NaN,25-44,BLACK,M

In [3]:
df

,CMPLNT_NUM,CMPLNT_FR_DT,CMPLNT_FR_TM,CMPLNT_TO_DT,CMPLNT_TO_TM,ADDR_PCT_CD,RPT_DT,KY_CD,OFNS_DESC,PD_CD,PD_DESC,CRM_ATPT_CPTD_CD,LAW_CAT_CD,BORO_NM,LOC_OF_OCCUR_DESC,PREM_TYP_DESC,JURIS_DESC,JURISDICTION_CODE,PARKS_NM,HADEVELOPT,HOUSING_PSA,X_COORD_CD,Y_COORD_CD,SUSP_AGE_GROUP,SUSP_RACE,SUSP_SEX,TRANSIT_DISTRICT,Latitude,Longitude,Lat_Lon,PATROL_BORO,STATION_NAME,VIC_AGE_GROUP,VIC_RACE,VIC_SEX
0,724718389,09/04/2014,17:25:00,09/04/2014,17:35:00,81.0,09/04/2014,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,BROOKLYN,OPPOSITE OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1005945.0,188862.0,NaN,NaN,NaN,NaN,40.685041,-73.921777,"(40.685040958, -73.921776995)",PATROL BORO BKLYN NORTH,NaN,25-44,WHITE,F
1,191133903,10/12/2016,07:40:00,10/12/2016,07:45:00,121.0,10/12/2016,109,GRAND LARCENY,417.0,"LARCENY,GRAND FROM PERSON,PURS",COMPLETED,FELONY,STATEN ISLAND,NaN,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,947034.0,171375.0,UNKNOWN,BLACK,U,NaN,40.636991,-74.134093,"(40.63699139, -74.134092508)",PATROL BORO STATEN ISLAND,NaN,45-64,WHITE HISPANIC,F
2,720151206,09/28/2012,13:30:00,09/28/2012,14:00:00,41.0,10/19/2012,109,GRAND LARCENY,413.0,"LARCENY,GRAND BY FALSE PROMISE",COMPLETED,FELONY,BRONX,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1014179.0,239453.0,NaN,WHITE HISPANIC,M,NaN,40.823876,-73.891863,"(40.823876276, -73.891862968)",PATROL BORO BRONX,NaN,45-64,WHITE HISPANIC,F
3,232242098,03/24/2015,15:45:00,NaN,NaN,46.0,03/24/2015,341,PETIT LARCENY,339.0,"LARCENY,PETIT FROM OPEN AREAS,",COMPLETED,MISDEMEANOR,BRONX,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1009041.0,247401.0,NaN,BLACK,M,NaN,40.845707,-73.910398,"(40.845707148, -73.910398033)",PATROL BORO BRONX,NaN,<18,WHITE HISPANIC,F
4,708078702,05/20/2017,04:02:00,05/20/2017,04:09:00,109.0,05/20/2017,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,QUEENS,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,1031779.0,217663.0,25-44,WHITE HISPANIC,M,NaN,40.763992,-73.828426,"(40.763991557, -73.828425559)",PATROL BORO QUEENS NORTH,NaN,25-44,BLACK,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6983202,202934942,09/12/2014,17:50:00,09/12/2014,17:55:00,28.0,09/12/2014,341,PETIT LARCENY,333.0,"LARCENY,PETIT FROM STORE-SHOPL",COMPLETED,MISDEMEANOR,MANHATTAN,INSIDE,COMMERCIAL BUILDING,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,998954.0,233791.0,NaN,NaN,NaN,NaN,40.808374,-73.946886,"(40.808374136, -73.946885823)",PATROL BORO MAN NORTH,NaN,NaN,UNKNOWN,D
6983203,327134526,12/20/2012,13:30:00,12/20/2012,13:35:00,70.0,12/20/2012,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,BROOKLYN,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,993205.0,175595.0,NaN,NaN,NaN,NaN,40.648648,-73.967731,"(40.648648047, -73.967730515)",PATROL BORO BKLYN SOUTH,NaN,25-44,BLACK,F
6983204,671421638,04/04/2013,13:00:00,04/04/2013,15:30:00,90.0,04/04/2013,341,PETIT LARCENY,321.0,"LARCENY,PETIT FROM AUTO",COMPLETED,MISDEMEANOR,BROOKLYN,FRONT OF,STREET,N.Y. POLICE DEPT,0.0,NaN,NaN,NaN,994185.0,200150.0,NaN,NaN,NaN,NaN,40.716045,-73.964163,"(40.716044892, -73.964162712)",PATROL BORO BKLYN NORTH,NaN,45-64,WHITE,M
6983205,980011525,09/09/2015,13:00:00,09/09/2015,13:50:00,13.0,09/09/2015,360,NaN,649.0,FALSE REPORT UNCLASSIFIED,COMPLETED,MISDEMEANOR,MANHATTAN,NaN,TRANSIT - NYC SUBWAY,N.Y. TRANSIT POLICE,1.0,NaN,NaN,NaN,986553.0,207131.0,NaN,NaN,NaN,4.0,40.735211,-73.991691,"(40.735211323, -73.991691398)",PATROL BORO MAN SOUTH,DISTRICT 4 OFFICE,NaN,UNKNOWN,E
6983206,719347170,08/19/2012,01:00:00,08/19/2012,01:30:00,73.0,08/19/2012,344,ASSAULT 3 & RELATED OFFENSES,101.0,ASSAULT 3,COMPLETED,MISDEMEANOR,BROOKLYN,FRONT OF,RESIDENCE - PUBLIC HOUSING,N.Y. HOUSING POLICE,2.0,NaN,HUGHES APARTMENTS,361.0,1009968.0,182502.0,NaN,BLACK,M,NaN,40.667573,-73.907296,"(40.667573424, -73.907295766)",PATROL BORO BKLYN NORTH,NaN,25-44,BLACK,F

In [37]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
CMPLNT_NUM,6983207.0,5.500768e+08,2.597838e+08,1.000001e+08,3.252107e+08,5.500624e+08,7.750561e+08,9.999999e+08
ADDR_PCT_CD,6981041.0,6.327224e+01,3.451961e+01,-9.900000e+01,4.000000e+01,6.300000e+01,9.400000e+01,1.230000e+02
KY_CD,6983207.0,2.957909e+02,1.499370e+02,1.010000e+02,1.170000e+02,3.410000e+02,3.510000e+02,8.810000e+02
PD_CD,6977342.0,4.148457e+02,2.180586e+02,1.000000e+02,2.540000e+02,3.860000e+02,6.370000e+02,9.750000e+02
JURISDICTION_CODE,6977342.0,7.304343e-01,6.752324e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.700000e+01
X_COORD_CD,6959143.0,1.004796e+06,2.174732e+04,1.110000e+02,9.916830e+05,1.004370e+06,1.016586e+06,1.067298e+06
Y_COORD_CD,6959143.0,2.070544e+05,3.153994e+04,1.110000e+02,1.843520e+05,2.059660e+05,2.351580e+05,7.250292e+06
TRANSIT_DISTRICT,157084.0,1.359840e+01,1.247143e+01,1.000000e+00,3.000000e+00,1.100000e+01,3.000000e+01,3.400000e+01
Latitude,6959143.0,4.073495e+01,8.647664e-02,4.011271e+01,4.067261e+01,4.073196e+01,4.081212e+01,5.965727e+01
Longitude,6959143.0,-7.392583e+01,7.842862e-02,-7.751921e+01,-7.397323e+01,-7.392733e+01,-7.388325e+01,-7.368479e+01

In [38]:
#Sum of nan values
df.isnull().sum()

CMPLNT_NUM                 0
CMPLNT_FR_DT             655
CMPLNT_FR_TM              48
CMPLNT_TO_DT         1668376
CMPLNT_TO_TM         1663829
ADDR_PCT_CD             2166
RPT_DT                     0
KY_CD                      0
OFNS_DESC              18825
PD_CD                   5865
PD_DESC                 5865
CRM_ATPT_CPTD_CD           7
LAW_CAT_CD                 0
BORO_NM                10894
LOC_OF_OCCUR_DESC    1479992
PREM_TYP_DESC          39732
JURIS_DESC                 0
JURISDICTION_CODE       5865
PARKS_NM             6958159
HADEVELOPT           6637179
HOUSING_PSA          6446298
X_COORD_CD             24064
Y_COORD_CD             24064
SUSP_AGE_GROUP       4707573
SUSP_RACE            3339032
SUSP_SEX             3472346
TRANSIT_DISTRICT     6826123
Latitude               24064
Longitude              24064
Lat_Lon                24064
PATROL_BORO             6322
STATION_NAME         6826123
VIC_AGE_GROUP        1638444
VIC_RACE                 308
VIC_SEX                  307
dtype: int64

In [39]:
#Calculating percentage of null values
for column in df.columns:
    print(f'{column}:missing {df[column].isna().sum()*100/len(df)}')

CMPLNT_NUM:missing 0.0
CMPLNT_FR_DT:missing 0.009379644624597266
CMPLNT_FR_TM:missing 0.0006873632701994943
CMPLNT_TO_DT:missing 23.89125798504899
CMPLNT_TO_TM:missing 23.826144635265717
ADDR_PCT_CD:missing 0.03101726756775218
RPT_DT:missing 0.0
KY_CD:missing 0.0
OFNS_DESC:missing 0.26957528253136415
PD_CD:missing 0.08398719957750071
PD_DESC:missing 0.08398719957750071
CRM_ATPT_CPTD_CD:missing 0.00010024047690409292
LAW_CAT_CD:missing 0.0
BORO_NM:missing 0.1560028221990269
LOC_OF_OCCUR_DESC:missing 21.19358627060604
PREM_TYP_DESC:missing 0.5689649469076314
JURIS_DESC:missing 0.0
JURISDICTION_CODE:missing 0.08398719957750071
PARKS_NM:missing 99.6413109335009
HADEVELOPT:missing 95.04485546540437
HOUSING_PSA:missing 92.31142654084292
X_COORD_CD:missing 0.3445981194600131
Y_COORD_CD:missing 0.3445981194600131
SUSP_AGE_GROUP:missing 67.41276608297592
SUSP_RACE:missing 47.81516572543246
SUSP_SEX:missing 49.72423128800278
TRANSIT_DISTRICT:missing 97.75054641799964
Latitude:missing 0.3445981194600131
Longitude:missing 0.3445981194600131
Lat_Lon:missing 0.3445981194600131
PATROL_BORO:missing 0.09053147071252506
STATION_NAME:missing 97.75054641799964
VIC_AGE_GROUP:missing 23.46262970580709
VIC_RACE:missing 0.0044105809837800885
VIC_SEX:missing 0.004396260915650933

In [40]:
# drop useless columns
df.drop(columns = ['SUSP_AGE_GROUP', 'SUSP_RACE', 'SUSP_SEX','JURISDICTION_CODE','JURIS_DESC','PD_CD','PD_DESC','HADEVELOPT','KY_CD','CMPLNT_NUM','RPT_DT','LOC_OF_OCCUR_DESC','Lat_Lon','X_COORD_CD','Y_COORD_CD','PARKS_NM','TRANSIT_DISTRICT','STATION_NAME','HOUSING_PSA',],inplace = True)

Data pre-processing

In [41]:
df.columns

Index(['CMPLNT_FR_DT', 'CMPLNT_FR_TM', 'CMPLNT_TO_DT', 'CMPLNT_TO_TM',
       'ADDR_PCT_CD', 'OFNS_DESC', 'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'BORO_NM',
       'PREM_TYP_DESC', 'Latitude', 'Longitude', 'PATROL_BORO',
       'VIC_AGE_GROUP', 'VIC_RACE', 'VIC_SEX'],
      dtype='object')

In [42]:
df = df[df['CMPLNT_FR_DT'].notna()]

In [43]:
df.isnull().sum()

CMPLNT_FR_DT              0
CMPLNT_FR_TM             47
CMPLNT_TO_DT        1668229
CMPLNT_TO_TM        1663691
ADDR_PCT_CD            2166
OFNS_DESC             18824
CRM_ATPT_CPTD_CD          7
LAW_CAT_CD                0
BORO_NM               10893
PREM_TYP_DESC         39730
Latitude              24057
Longitude             24057
PATROL_BORO            6322
VIC_AGE_GROUP       1638330
VIC_RACE                308
VIC_SEX                 307
dtype: int64

In [45]:
# Rows without coordinates should be dropped
df = df[df['Latitude'].notna()]
df = df[df['Longitude'].notna()]

In [46]:
# check duplicate values
if all(df['CMPLNT_FR_DT'].notna() == df['CMPLNT_TO_DT'].notna()):
    df.drop(columns='CMPLNT_TO_DT',inplace = True)

In [47]:
# change date columns to YYYY-MM-DD
df['CMPLNT_FR_DT']= pd.to_datetime(df['CMPLNT_FR_DT'],errors='coerce')
df['CMPLNT_FR_TM'] = pd.to_datetime(df['CMPLNT_FR_TM'],errors='coerce')

In [48]:
# delete columns that have no event start date or time
df = df[df['CMPLNT_FR_DT'].notna()]
df = df[df['CMPLNT_FR_TM'].notna()]

In [49]:
# split date to year, month and day
df['year'] = df['CMPLNT_FR_DT'].dt.year
df['month'] = df['CMPLNT_FR_DT'].dt.month
df['day'] = df['CMPLNT_FR_DT'].dt.day
df['hour'] =df['CMPLNT_FR_TM'].dt.hour
# add week day column
df['weekday'] = pd.to_datetime(df['CMPLNT_FR_DT']).dt.day_name()
df.drop(columns='CMPLNT_FR_DT',inplace = True)
df.drop(columns='CMPLNT_FR_TM',inplace = True)

In [51]:
# take care of unvalid age data
age_range = ['UNKNOWN', '<18','18-24', '25-44', '45-64','65+']
df.loc[~df['VIC_AGE_GROUP'].isin(age_range),'VIC_AGE_GROUP'] = 'UNKNOWN'

In [52]:
df.columns

Index(['CMPLNT_TO_DT', 'CMPLNT_TO_TM', 'ADDR_PCT_CD', 'OFNS_DESC',
       'CRM_ATPT_CPTD_CD', 'LAW_CAT_CD', 'BORO_NM', 'PREM_TYP_DESC',
       'Latitude', 'Longitude', 'PATROL_BORO', 'VIC_AGE_GROUP', 'VIC_RACE',
       'VIC_SEX', 'year', 'month', 'day', 'hour', 'weekday'],
      dtype='object')

In [53]:
# these columns have redundent info
df.drop(columns='CMPLNT_TO_TM',inplace = True)
df.drop(columns='CMPLNT_TO_DT',inplace = True)

In [54]:
df['VIC_SEX'] = df['VIC_SEX'].fillna('U')

In [55]:
df['VIC_SEX'].unique()

array(['F', 'M', 'D', 'E', 'U'], dtype=object)

In [56]:
sex_range =  ['F','M']
df.loc[~df['VIC_SEX'].isin(sex_range),'VIC_SEX'] = 'UNKNOWN'

In [57]:
df.isnull().sum()

ADDR_PCT_CD          1329
OFNS_DESC           18706
CRM_ATPT_CPTD_CD        7
LAW_CAT_CD              0
BORO_NM             10418
PREM_TYP_DESC       38671
Latitude                0
Longitude               0
PATROL_BORO          5470
VIC_AGE_GROUP           0
VIC_RACE              308
VIC_SEX                 0
year                    0
month                   0
day                     0
hour                    0
weekday                 0
dtype: int64

In [58]:
#Delete nan values for CRM_ATPT_CPTD_CD
df = df.dropna(subset=['CRM_ATPT_CPTD_CD'])

In [59]:
# redundent data
df.drop(columns='PATROL_BORO',inplace = True)
df['BORO_NM'] = df['BORO_NM'].fillna('UNKNOWN')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1568\1183454152.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns='PATROL_BORO',inplace = True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1568\1183454152.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BORO_NM'] = df['BORO_NM'].fillna('UNKNOWN')

In [60]:
df.dropna(inplace=True)
len(df)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1568\2888176961.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

6900865

In [61]:
# encode crime severity
df['LAW_CAT_CD'] = df['LAW_CAT_CD'].replace(['Felony','Misdemeanor','Violation'],[2,1,0])

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_1568\3772361186.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['LAW_CAT_CD'] = df['LAW_CAT_CD'].replace(['Felony','Misdemeanor','Violation'],[2,1,0])

In [62]:
df['LAW_CAT_CD'].value_counts()

MISDEMEANOR    3887974
FELONY         2124197
VIOLATION       888694
Name: LAW_CAT_CD, dtype: int64

In [63]:
df.to_csv('Data_cleaned_version.csv')